server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: traveler
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${host}:3306/traveler?serverTimezone=Asia/Shanghai
    username: root
    password: ${password}
  data:
    redis:
      host: localhost
      port: 6379
      password: ${password}
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
  web:
    resources:
      add-mappings: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.soldiersoft.traveler.mapper: debug

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
