server:
  port: 8080

spring:
  application:
    name: traveler
  mail:
    protocol: smtp
    host: smtp.163.com
#    port: 465
    username: soldierrmb0510@163.com
    password: TWFCFLFWOXHEZNHU
    default-encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/traveler?serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: 7355608
  data:
    redis:
      host: localhost
      port: 6379
      password: 7355608
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
  web:
    resources:
      add-mappings: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.soldiersoft.traveler.mapper: debug

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
